%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'EA_SWW14_rep';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(8,1);
M_.exo_names_tex = cell(8,1);
M_.exo_names_long = cell(8,1);
M_.exo_names(1) = {'etab'};
M_.exo_names_tex(1) = {'etab'};
M_.exo_names_long(1) = {'etab'};
M_.exo_names(2) = {'etaq'};
M_.exo_names_tex(2) = {'etaq'};
M_.exo_names_long(2) = {'etaq'};
M_.exo_names(3) = {'etag'};
M_.exo_names_tex(3) = {'etag'};
M_.exo_names_long(3) = {'etag'};
M_.exo_names(4) = {'etaa'};
M_.exo_names_tex(4) = {'etaa'};
M_.exo_names_long(4) = {'etaa'};
M_.exo_names(5) = {'etap'};
M_.exo_names_tex(5) = {'etap'};
M_.exo_names_long(5) = {'etap'};
M_.exo_names(6) = {'etas'};
M_.exo_names_tex(6) = {'etas'};
M_.exo_names_long(6) = {'etas'};
M_.exo_names(7) = {'etaw'};
M_.exo_names_tex(7) = {'etaw'};
M_.exo_names_long(7) = {'etaw'};
M_.exo_names(8) = {'etar'};
M_.exo_names_tex(8) = {'etar'};
M_.exo_names_long(8) = {'etar'};
M_.endo_names = cell(54,1);
M_.endo_names_tex = cell(54,1);
M_.endo_names_long = cell(54,1);
M_.endo_names(1) = {'c'};
M_.endo_names_tex(1) = {'c'};
M_.endo_names_long(1) = {'c'};
M_.endo_names(2) = {'r'};
M_.endo_names_tex(2) = {'r'};
M_.endo_names_long(2) = {'r'};
M_.endo_names(3) = {'pi'};
M_.endo_names_tex(3) = {'pi'};
M_.endo_names_long(3) = {'pi'};
M_.endo_names(4) = {'i'};
M_.endo_names_tex(4) = {'i'};
M_.endo_names_long(4) = {'i'};
M_.endo_names(5) = {'q'};
M_.endo_names_tex(5) = {'q'};
M_.endo_names_long(5) = {'q'};
M_.endo_names(6) = {'rk'};
M_.endo_names_tex(6) = {'rk'};
M_.endo_names_long(6) = {'rk'};
M_.endo_names(7) = {'y'};
M_.endo_names_tex(7) = {'y'};
M_.endo_names_long(7) = {'y'};
M_.endo_names(8) = {'v'};
M_.endo_names_tex(8) = {'v'};
M_.endo_names_long(8) = {'v'};
M_.endo_names(9) = {'k'};
M_.endo_names_tex(9) = {'k'};
M_.endo_names_long(9) = {'k'};
M_.endo_names(10) = {'n'};
M_.endo_names_tex(10) = {'n'};
M_.endo_names_long(10) = {'n'};
M_.endo_names(11) = {'mc'};
M_.endo_names_tex(11) = {'mc'};
M_.endo_names_long(11) = {'mc'};
M_.endo_names(12) = {'w'};
M_.endo_names_tex(12) = {'w'};
M_.endo_names_long(12) = {'w'};
M_.endo_names(13) = {'z'};
M_.endo_names_tex(13) = {'z'};
M_.endo_names_long(13) = {'z'};
M_.endo_names(14) = {'u'};
M_.endo_names_tex(14) = {'u'};
M_.endo_names_long(14) = {'u'};
M_.endo_names(15) = {'e'};
M_.endo_names_tex(15) = {'e'};
M_.endo_names_long(15) = {'e'};
M_.endo_names(16) = {'un'};
M_.endo_names_tex(16) = {'un'};
M_.endo_names_long(16) = {'un'};
M_.endo_names(17) = {'l'};
M_.endo_names_tex(17) = {'l'};
M_.endo_names_long(17) = {'l'};
M_.endo_names(18) = {'kbar'};
M_.endo_names_tex(18) = {'kbar'};
M_.endo_names_long(18) = {'kbar'};
M_.endo_names(19) = {'ygap'};
M_.endo_names_tex(19) = {'ygap'};
M_.endo_names_long(19) = {'ygap'};
M_.endo_names(20) = {'cf'};
M_.endo_names_tex(20) = {'cf'};
M_.endo_names_long(20) = {'cf'};
M_.endo_names(21) = {'rf'};
M_.endo_names_tex(21) = {'rf'};
M_.endo_names_long(21) = {'rf'};
M_.endo_names(22) = {'invf'};
M_.endo_names_tex(22) = {'invf'};
M_.endo_names_long(22) = {'invf'};
M_.endo_names(23) = {'qf'};
M_.endo_names_tex(23) = {'qf'};
M_.endo_names_long(23) = {'qf'};
M_.endo_names(24) = {'rkf'};
M_.endo_names_tex(24) = {'rkf'};
M_.endo_names_long(24) = {'rkf'};
M_.endo_names(25) = {'vf'};
M_.endo_names_tex(25) = {'vf'};
M_.endo_names_long(25) = {'vf'};
M_.endo_names(26) = {'kf'};
M_.endo_names_tex(26) = {'kf'};
M_.endo_names_long(26) = {'kf'};
M_.endo_names(27) = {'nf'};
M_.endo_names_tex(27) = {'nf'};
M_.endo_names_long(27) = {'nf'};
M_.endo_names(28) = {'wf'};
M_.endo_names_tex(28) = {'wf'};
M_.endo_names_long(28) = {'wf'};
M_.endo_names(29) = {'zf'};
M_.endo_names_tex(29) = {'zf'};
M_.endo_names_long(29) = {'zf'};
M_.endo_names(30) = {'ef'};
M_.endo_names_tex(30) = {'ef'};
M_.endo_names_long(30) = {'ef'};
M_.endo_names(31) = {'kbarf'};
M_.endo_names_tex(31) = {'kbarf'};
M_.endo_names_long(31) = {'kbarf'};
M_.endo_names(32) = {'yf'};
M_.endo_names_tex(32) = {'yf'};
M_.endo_names_long(32) = {'yf'};
M_.endo_names(33) = {'epsilonb'};
M_.endo_names_tex(33) = {'epsilonb'};
M_.endo_names_long(33) = {'epsilonb'};
M_.endo_names(34) = {'epsilonq'};
M_.endo_names_tex(34) = {'epsilonq'};
M_.endo_names_long(34) = {'epsilonq'};
M_.endo_names(35) = {'epsilong'};
M_.endo_names_tex(35) = {'epsilong'};
M_.endo_names_long(35) = {'epsilong'};
M_.endo_names(36) = {'epsilona'};
M_.endo_names_tex(36) = {'epsilona'};
M_.endo_names_long(36) = {'epsilona'};
M_.endo_names(37) = {'epsilonp'};
M_.endo_names_tex(37) = {'epsilonp'};
M_.endo_names_long(37) = {'epsilonp'};
M_.endo_names(38) = {'epsilons'};
M_.endo_names_tex(38) = {'epsilons'};
M_.endo_names_long(38) = {'epsilons'};
M_.endo_names(39) = {'epsilonw'};
M_.endo_names_tex(39) = {'epsilonw'};
M_.endo_names_long(39) = {'epsilonw'};
M_.endo_names(40) = {'epsilonr'};
M_.endo_names_tex(40) = {'epsilonr'};
M_.endo_names_long(40) = {'epsilonr'};
M_.endo_names(41) = {'dyobs'};
M_.endo_names_tex(41) = {'dyobs'};
M_.endo_names_long(41) = {'dyobs'};
M_.endo_names(42) = {'dcobs'};
M_.endo_names_tex(42) = {'dcobs'};
M_.endo_names_long(42) = {'dcobs'};
M_.endo_names(43) = {'diobs'};
M_.endo_names_tex(43) = {'diobs'};
M_.endo_names_long(43) = {'diobs'};
M_.endo_names(44) = {'piobs'};
M_.endo_names_tex(44) = {'piobs'};
M_.endo_names_long(44) = {'piobs'};
M_.endo_names(45) = {'dwobs'};
M_.endo_names_tex(45) = {'dwobs'};
M_.endo_names_long(45) = {'dwobs'};
M_.endo_names(46) = {'deobs'};
M_.endo_names_tex(46) = {'deobs'};
M_.endo_names_long(46) = {'deobs'};
M_.endo_names(47) = {'uobs'};
M_.endo_names_tex(47) = {'uobs'};
M_.endo_names_long(47) = {'uobs'};
M_.endo_names(48) = {'robs'};
M_.endo_names_tex(48) = {'robs'};
M_.endo_names_long(48) = {'robs'};
M_.endo_names(49) = {'ryear'};
M_.endo_names_tex(49) = {'ryear'};
M_.endo_names_long(49) = {'ryear'};
M_.endo_names(50) = {'piyear'};
M_.endo_names_tex(50) = {'piyear'};
M_.endo_names_long(50) = {'piyear'};
M_.endo_names(51) = {'AUX_ENDO_LAG_2_1'};
M_.endo_names_tex(51) = {'AUX\_ENDO\_LAG\_2\_1'};
M_.endo_names_long(51) = {'AUX_ENDO_LAG_2_1'};
M_.endo_names(52) = {'AUX_ENDO_LAG_2_2'};
M_.endo_names_tex(52) = {'AUX\_ENDO\_LAG\_2\_2'};
M_.endo_names_long(52) = {'AUX_ENDO_LAG_2_2'};
M_.endo_names(53) = {'AUX_EXO_LAG_54_0'};
M_.endo_names_tex(53) = {'AUX\_EXO\_LAG\_54\_0'};
M_.endo_names_long(53) = {'AUX_EXO_LAG_54_0'};
M_.endo_names(54) = {'AUX_EXO_LAG_56_0'};
M_.endo_names_tex(54) = {'AUX\_EXO\_LAG\_56\_0'};
M_.endo_names_long(54) = {'AUX_EXO_LAG_56_0'};
M_.endo_partitions = struct();
M_.param_names = cell(59,1);
M_.param_names_tex = cell(59,1);
M_.param_names_long = cell(59,1);
M_.param_names(1) = {'ch'};
M_.param_names_tex(1) = {'ch'};
M_.param_names_long(1) = {'ch'};
M_.param_names(2) = {'ctau'};
M_.param_names_tex(2) = {'ctau'};
M_.param_names_long(2) = {'ctau'};
M_.param_names(3) = {'cbeta'};
M_.param_names_tex(3) = {'cbeta'};
M_.param_names_long(3) = {'cbeta'};
M_.param_names(4) = {'cphi'};
M_.param_names_tex(4) = {'cphi'};
M_.param_names_long(4) = {'cphi'};
M_.param_names(5) = {'cdelta'};
M_.param_names_tex(5) = {'cdelta'};
M_.param_names_long(5) = {'cdelta'};
M_.param_names(6) = {'cpsip'};
M_.param_names_tex(6) = {'cpsip'};
M_.param_names_long(6) = {'cpsip'};
M_.param_names(7) = {'calpha'};
M_.param_names_tex(7) = {'calpha'};
M_.param_names_long(7) = {'calpha'};
M_.param_names(8) = {'cgammap'};
M_.param_names_tex(8) = {'cgammap'};
M_.param_names_long(8) = {'cgammap'};
M_.param_names(9) = {'cthetap'};
M_.param_names_tex(9) = {'cthetap'};
M_.param_names_long(9) = {'cthetap'};
M_.param_names(10) = {'cepsp'};
M_.param_names_tex(10) = {'cepsp'};
M_.param_names_long(10) = {'cepsp'};
M_.param_names(11) = {'cgammaw'};
M_.param_names_tex(11) = {'cgammaw'};
M_.param_names_long(11) = {'cgammaw'};
M_.param_names(12) = {'cthetaw'};
M_.param_names_tex(12) = {'cthetaw'};
M_.param_names_long(12) = {'cthetaw'};
M_.param_names(13) = {'cepsw'};
M_.param_names_tex(13) = {'cepsw'};
M_.param_names_long(13) = {'cepsw'};
M_.param_names(14) = {'comega'};
M_.param_names_tex(14) = {'comega'};
M_.param_names_long(14) = {'comega'};
M_.param_names(15) = {'cv'};
M_.param_names_tex(15) = {'cv'};
M_.param_names_long(15) = {'cv'};
M_.param_names(16) = {'cpsi'};
M_.param_names_tex(16) = {'cpsi'};
M_.param_names_long(16) = {'cpsi'};
M_.param_names(17) = {'crhointr'};
M_.param_names_tex(17) = {'crhointr'};
M_.param_names_long(17) = {'crhointr'};
M_.param_names(18) = {'crpi'};
M_.param_names_tex(18) = {'crpi'};
M_.param_names_long(18) = {'crpi'};
M_.param_names(19) = {'cry'};
M_.param_names_tex(19) = {'cry'};
M_.param_names_long(19) = {'cry'};
M_.param_names(20) = {'crdy'};
M_.param_names_tex(20) = {'crdy'};
M_.param_names_long(20) = {'crdy'};
M_.param_names(21) = {'cthetae'};
M_.param_names_tex(21) = {'cthetae'};
M_.param_names_long(21) = {'cthetae'};
M_.param_names(22) = {'crk'};
M_.param_names_tex(22) = {'crk'};
M_.param_names_long(22) = {'crk'};
M_.param_names(23) = {'ccy'};
M_.param_names_tex(23) = {'ccy'};
M_.param_names_long(23) = {'ccy'};
M_.param_names(24) = {'ciy'};
M_.param_names_tex(24) = {'ciy'};
M_.param_names_long(24) = {'ciy'};
M_.param_names(25) = {'cvy'};
M_.param_names_tex(25) = {'cvy'};
M_.param_names_long(25) = {'cvy'};
M_.param_names(26) = {'cgy'};
M_.param_names_tex(26) = {'cgy'};
M_.param_names_long(26) = {'cgy'};
M_.param_names(27) = {'cky'};
M_.param_names_tex(27) = {'cky'};
M_.param_names_long(27) = {'cky'};
M_.param_names(28) = {'ctaubar'};
M_.param_names_tex(28) = {'ctaubar'};
M_.param_names_long(28) = {'ctaubar'};
M_.param_names(29) = {'cpi'};
M_.param_names_tex(29) = {'cpi'};
M_.param_names_long(29) = {'cpi'};
M_.param_names(30) = {'cpibar'};
M_.param_names_tex(30) = {'cpibar'};
M_.param_names_long(30) = {'cpibar'};
M_.param_names(31) = {'crbar'};
M_.param_names_tex(31) = {'crbar'};
M_.param_names_long(31) = {'crbar'};
M_.param_names(32) = {'cubar'};
M_.param_names_tex(32) = {'cubar'};
M_.param_names_long(32) = {'cubar'};
M_.param_names(33) = {'cebar'};
M_.param_names_tex(33) = {'cebar'};
M_.param_names_long(33) = {'cebar'};
M_.param_names(34) = {'cbetabar'};
M_.param_names_tex(34) = {'cbetabar'};
M_.param_names_long(34) = {'cbetabar'};
M_.param_names(35) = {'cpsiw'};
M_.param_names_tex(35) = {'cpsiw'};
M_.param_names_long(35) = {'cpsiw'};
M_.param_names(36) = {'clk'};
M_.param_names_tex(36) = {'clk'};
M_.param_names_long(36) = {'clk'};
M_.param_names(37) = {'cw'};
M_.param_names_tex(37) = {'cw'};
M_.param_names_long(37) = {'cw'};
M_.param_names(38) = {'c1'};
M_.param_names_tex(38) = {'c1'};
M_.param_names_long(38) = {'c1'};
M_.param_names(39) = {'c2'};
M_.param_names_tex(39) = {'c2'};
M_.param_names_long(39) = {'c2'};
M_.param_names(40) = {'i1'};
M_.param_names_tex(40) = {'i1'};
M_.param_names_long(40) = {'i1'};
M_.param_names(41) = {'i2'};
M_.param_names_tex(41) = {'i2'};
M_.param_names_long(41) = {'i2'};
M_.param_names(42) = {'q1'};
M_.param_names_tex(42) = {'q1'};
M_.param_names_long(42) = {'q1'};
M_.param_names(43) = {'pi1'};
M_.param_names_tex(43) = {'pi1'};
M_.param_names_long(43) = {'pi1'};
M_.param_names(44) = {'pi2'};
M_.param_names_tex(44) = {'pi2'};
M_.param_names_long(44) = {'pi2'};
M_.param_names(45) = {'w1'};
M_.param_names_tex(45) = {'w1'};
M_.param_names_long(45) = {'w1'};
M_.param_names(46) = {'k1'};
M_.param_names_tex(46) = {'k1'};
M_.param_names_long(46) = {'k1'};
M_.param_names(47) = {'k2'};
M_.param_names_tex(47) = {'k2'};
M_.param_names_long(47) = {'k2'};
M_.param_names(48) = {'e1'};
M_.param_names_tex(48) = {'e1'};
M_.param_names_long(48) = {'e1'};
M_.param_names(49) = {'crhob'};
M_.param_names_tex(49) = {'crhob'};
M_.param_names_long(49) = {'crhob'};
M_.param_names(50) = {'crhoq'};
M_.param_names_tex(50) = {'crhoq'};
M_.param_names_long(50) = {'crhoq'};
M_.param_names(51) = {'crhog'};
M_.param_names_tex(51) = {'crhog'};
M_.param_names_long(51) = {'crhog'};
M_.param_names(52) = {'crhoa'};
M_.param_names_tex(52) = {'crhoa'};
M_.param_names_long(52) = {'crhoa'};
M_.param_names(53) = {'crhoga'};
M_.param_names_tex(53) = {'crhoga'};
M_.param_names_long(53) = {'crhoga'};
M_.param_names(54) = {'crhop'};
M_.param_names_tex(54) = {'crhop'};
M_.param_names_long(54) = {'crhop'};
M_.param_names(55) = {'cmup'};
M_.param_names_tex(55) = {'cmup'};
M_.param_names_long(55) = {'cmup'};
M_.param_names(56) = {'crhos'};
M_.param_names_tex(56) = {'crhos'};
M_.param_names_long(56) = {'crhos'};
M_.param_names(57) = {'crhow'};
M_.param_names_tex(57) = {'crhow'};
M_.param_names_long(57) = {'crhow'};
M_.param_names(58) = {'cmuw'};
M_.param_names_tex(58) = {'cmuw'};
M_.param_names_long(58) = {'cmuw'};
M_.param_names(59) = {'crhor'};
M_.param_names_tex(59) = {'crhor'};
M_.param_names_long(59) = {'crhor'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 8;
M_.endo_nbr = 54;
M_.param_nbr = 59;
M_.orig_endo_nbr = 50;
M_.aux_vars(1).endo_index = 51;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 3;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'pi(-1)';
M_.aux_vars(2).endo_index = 52;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 3;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LAG_2_1(-1)';
M_.aux_vars(3).endo_index = 53;
M_.aux_vars(3).type = 3;
M_.aux_vars(3).orig_index = 5;
M_.aux_vars(3).orig_lead_lag = 0;
M_.aux_vars(3).orig_expr = 'etap';
M_.aux_vars(4).endo_index = 54;
M_.aux_vars(4).type = 3;
M_.aux_vars(4).orig_index = 7;
M_.aux_vars(4).orig_lead_lag = 0;
M_.aux_vars(4).orig_expr = 'etaw';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(8, 8);
M_.Correlation_matrix = eye(8, 8);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 50;
M_.eq_nbr = 54;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 3;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 1;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 3;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 3;
M_.lead_lag_incidence = [
 1 28 82;
 2 29 0;
 3 30 83;
 4 31 84;
 0 32 85;
 0 33 86;
 5 34 0;
 0 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 6 39 87;
 7 40 0;
 0 41 0;
 8 42 88;
 0 43 0;
 0 44 0;
 9 45 0;
 10 46 0;
 11 47 89;
 0 48 0;
 12 49 90;
 0 50 91;
 0 51 92;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 13 56 0;
 14 57 93;
 15 58 0;
 0 59 0;
 16 60 0;
 17 61 0;
 18 62 0;
 19 63 0;
 20 64 0;
 21 65 0;
 22 66 0;
 23 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 24 78 0;
 25 79 0;
 26 80 0;
 27 81 0;]';
M_.nstatic = 23;
M_.nfwrd   = 4;
M_.npred   = 19;
M_.nboth   = 8;
M_.nsfwrd   = 12;
M_.nspred   = 27;
M_.ndynamic   = 31;
M_.dynamic_tmp_nbr = [2; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'c' ;
  2 , 'name' , 'i' ;
  3 , 'name' , 'q' ;
  4 , 'name' , 'y' ;
  5 , 'name' , '5' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'mc' ;
  8 , 'name' , '8' ;
  9 , 'name' , '9' ;
  10 , 'name' , '10' ;
  11 , 'name' , 'l' ;
  12 , 'name' , 'z' ;
  13 , 'name' , 'kbar' ;
  14 , 'name' , 'k' ;
  15 , 'name' , 'v' ;
  16 , 'name' , '16' ;
  17 , 'name' , 'r' ;
  18 , 'name' , '18' ;
  19 , 'name' , 'cf' ;
  20 , 'name' , 'invf' ;
  21 , 'name' , 'qf' ;
  22 , 'name' , 'yf' ;
  23 , 'name' , '23' ;
  24 , 'name' , '24' ;
  25 , 'name' , 'wf' ;
  26 , 'name' , 'zf' ;
  27 , 'name' , 'kbarf' ;
  28 , 'name' , 'kf' ;
  29 , 'name' , 'vf' ;
  30 , 'name' , '30' ;
  31 , 'name' , '31' ;
  32 , 'name' , 'ygap' ;
  33 , 'name' , 'epsilonb' ;
  34 , 'name' , 'epsilonq' ;
  35 , 'name' , 'epsilong' ;
  36 , 'name' , 'epsilona' ;
  37 , 'name' , 'epsilonp' ;
  38 , 'name' , 'epsilonr' ;
  39 , 'name' , 'epsilons' ;
  40 , 'name' , 'epsilonw' ;
  41 , 'name' , 'dyobs' ;
  42 , 'name' , 'dcobs' ;
  43 , 'name' , 'diobs' ;
  44 , 'name' , 'piobs' ;
  45 , 'name' , '45' ;
  46 , 'name' , 'deobs' ;
  47 , 'name' , 'uobs' ;
  48 , 'name' , 'robs' ;
  49 , 'name' , 'ryear' ;
  50 , 'name' , 'piyear' ;
};
M_.mapping.c.eqidx = [1 4 12 42 ];
M_.mapping.r.eqidx = [1 3 17 48 49 ];
M_.mapping.pi.eqidx = [1 3 6 8 17 44 45 50 ];
M_.mapping.i.eqidx = [2 4 13 43 ];
M_.mapping.q.eqidx = [2 3 ];
M_.mapping.rk.eqidx = [3 7 15 16 ];
M_.mapping.y.eqidx = [4 5 32 41 ];
M_.mapping.v.eqidx = [4 14 15 ];
M_.mapping.k.eqidx = [5 14 16 ];
M_.mapping.n.eqidx = [5 16 18 ];
M_.mapping.mc.eqidx = [6 7 ];
M_.mapping.w.eqidx = [7 8 9 16 45 ];
M_.mapping.z.eqidx = [9 12 ];
M_.mapping.u.eqidx = [8 9 11 47 ];
M_.mapping.e.eqidx = [9 11 18 46 ];
M_.mapping.un.eqidx = [10 ];
M_.mapping.l.eqidx = [11 ];
M_.mapping.kbar.eqidx = [13 14 ];
M_.mapping.ygap.eqidx = [17 32 ];
M_.mapping.cf.eqidx = [19 22 26 ];
M_.mapping.rf.eqidx = [19 21 ];
M_.mapping.invf.eqidx = [20 22 27 ];
M_.mapping.qf.eqidx = [20 21 ];
M_.mapping.rkf.eqidx = [21 24 29 30 ];
M_.mapping.vf.eqidx = [22 28 29 ];
M_.mapping.kf.eqidx = [23 28 30 ];
M_.mapping.nf.eqidx = [23 25 30 31 ];
M_.mapping.wf.eqidx = [24 25 30 ];
M_.mapping.zf.eqidx = [25 26 ];
M_.mapping.ef.eqidx = [31 ];
M_.mapping.kbarf.eqidx = [27 28 ];
M_.mapping.yf.eqidx = [22 23 32 ];
M_.mapping.epsilonb.eqidx = [1 3 19 21 33 ];
M_.mapping.epsilonq.eqidx = [2 13 20 27 34 ];
M_.mapping.epsilong.eqidx = [4 22 35 ];
M_.mapping.epsilona.eqidx = [5 7 23 24 36 ];
M_.mapping.epsilonp.eqidx = [6 37 ];
M_.mapping.epsilons.eqidx = [9 25 39 ];
M_.mapping.epsilonw.eqidx = [8 10 40 ];
M_.mapping.epsilonr.eqidx = [17 38 ];
M_.mapping.dyobs.eqidx = [41 ];
M_.mapping.dcobs.eqidx = [42 ];
M_.mapping.diobs.eqidx = [43 ];
M_.mapping.piobs.eqidx = [44 45 ];
M_.mapping.dwobs.eqidx = [45 ];
M_.mapping.deobs.eqidx = [46 ];
M_.mapping.uobs.eqidx = [47 ];
M_.mapping.robs.eqidx = [48 ];
M_.mapping.ryear.eqidx = [49 ];
M_.mapping.piyear.eqidx = [50 ];
M_.mapping.etab.eqidx = [33 ];
M_.mapping.etaq.eqidx = [34 ];
M_.mapping.etag.eqidx = [35 ];
M_.mapping.etaa.eqidx = [35 36 ];
M_.mapping.etap.eqidx = [37 ];
M_.mapping.etas.eqidx = [39 ];
M_.mapping.etaw.eqidx = [40 ];
M_.mapping.etar.eqidx = [38 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [1 2 3 4 7 12 13 15 18 19 20 22 29 30 31 33 34 35 36 37 38 39 40 51 52 53 54 ];
M_.exo_names_orig_ord = [1:8];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(54, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(8, 1);
M_.params = NaN(59, 1);
M_.endo_trends = struct('deflator', cell(54, 1), 'log_deflator', cell(54, 1), 'growth_factor', cell(54, 1), 'log_growth_factor', cell(54, 1));
M_.NNZDerivatives = [201; 0; -1; ];
M_.static_tmp_nbr = [1; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(5) = 0.025;
cdelta = M_.params(5);
M_.params(10) = 10;
cepsp = M_.params(10);
M_.params(26) = 0.18;
cgy = M_.params(26);
M_.params(56) = 0.999;
crhos = M_.params(56);
M_.params(1) = 0.635318;
ch = M_.params(1);
M_.params(4) = 4.630882;
cphi = M_.params(4);
M_.params(6) = 1.490662;
cpsip = M_.params(6);
M_.params(7) = 0.226791;
calpha = M_.params(7);
M_.params(8) = 0.250432;
cgammap = M_.params(8);
M_.params(9) = 0.842802;
cthetap = M_.params(9);
M_.params(11) = 0.251781;
cgammaw = M_.params(11);
M_.params(12) = 0.696311;
cthetaw = M_.params(12);
M_.params(35) = 1.500236;
cpsiw = M_.params(35);
M_.params(14) = 5.385964;
comega = M_.params(14);
M_.params(15) = 0.085281;
cv = M_.params(15);
M_.params(16) = 0.472810;
cpsi = M_.params(16);
M_.params(17) = 0.856383;
crhointr = M_.params(17);
M_.params(18) = 1.287264;
crpi = M_.params(18);
M_.params(19) = 0.192124;
cry = M_.params(19);
M_.params(20) = 0.016608;
crdy = M_.params(20);
M_.params(21) = 0.705567;
cthetae = M_.params(21);
M_.params(30) = 0.561370;
cpibar = M_.params(30);
M_.params(34) = 0.268560;
cbetabar = M_.params(34);
M_.params(33) = 0.226367;
cebar = M_.params(33);
M_.params(28) = 0.130848;
ctaubar = M_.params(28);
M_.params(2) = 1+M_.params(28)/100;
ctau = M_.params(2);
M_.params(3) = 1/(1+M_.params(34)/100);
cbeta = M_.params(3);
M_.params(29) = 1+M_.params(30)/100;
cpi = M_.params(29);
M_.params(32) = 100*(M_.params(35)-1)/M_.params(14);
cubar = M_.params(32);
M_.params(31) = 100*(M_.params(29)*M_.params(2)/M_.params(3)-1);
crbar = M_.params(31);
M_.params(13) = M_.params(35)/(M_.params(35)-1);
cepsw = M_.params(13);
M_.params(22) = M_.params(2)/M_.params(3)+M_.params(5)-1;
crk = M_.params(22);
M_.params(37) = (M_.params(7)^M_.params(7)*(1-M_.params(7))^(1-M_.params(7))/(M_.params(6)*M_.params(22)^M_.params(7)))^(1/(1-M_.params(7)));
cw = M_.params(37);
M_.params(36) = (1-M_.params(7))/M_.params(7)*M_.params(22)/M_.params(37);
clk = M_.params(36);
M_.params(27) = M_.params(6)*M_.params(36)^(M_.params(7)-1);
cky = M_.params(27);
M_.params(49) = 0.915697;
crhob = M_.params(49);
M_.params(50) = 0.345078;
crhoq = M_.params(50);
M_.params(51) = 0.992875;
crhog = M_.params(51);
M_.params(52) = 0.982716;
crhoa = M_.params(52);
M_.params(53) = 0.196454;
crhoga = M_.params(53);
M_.params(54) = 0.624064;
crhop = M_.params(54);
M_.params(55) = 0.570707;
cmup = M_.params(55);
M_.params(57) = 0.905390;
crhow = M_.params(57);
M_.params(58) = 0.826670;
cmuw = M_.params(58);
M_.params(59) = 0.316487;
crhor = M_.params(59);
M_.params(24) = (M_.params(2)+M_.params(5)-1)*M_.params(27);
ciy = M_.params(24);
M_.params(23) = 1-M_.params(24)-M_.params(26);
ccy = M_.params(23);
M_.params(25) = M_.params(22)*M_.params(27);
cvy = M_.params(25);
M_.params(38) = 1/(1+M_.params(1)/M_.params(2));
c1 = M_.params(38);
M_.params(39) = (1-M_.params(1)/M_.params(2))/(1+M_.params(1)/M_.params(2));
c2 = M_.params(39);
M_.params(40) = 1/(1+M_.params(3));
i1 = M_.params(40);
M_.params(41) = M_.params(40)/(M_.params(2)^2*M_.params(4));
i2 = M_.params(41);
M_.params(42) = M_.params(22)/(1+M_.params(22)-M_.params(5));
q1 = M_.params(42);
M_.params(43) = M_.params(3);
pi1 = M_.params(43);
M_.params(44) = (1-M_.params(3)*M_.params(9))*(1-M_.params(9))/(M_.params(9)*(1+(M_.params(6)-1)*M_.params(10)));
pi2 = M_.params(44);
M_.params(45) = (1-M_.params(3)*M_.params(12))*(1-M_.params(12))/(M_.params(12)*(1+M_.params(14)*M_.params(13)));
w1 = M_.params(45);
M_.params(46) = (1-M_.params(5))/M_.params(2);
k1 = M_.params(46);
M_.params(47) = M_.params(4)*M_.params(2)*(M_.params(2)+M_.params(5)-1)*(1+M_.params(3));
k2 = M_.params(47);
M_.params(48) = (1-M_.params(3)*M_.params(21))*(1-M_.params(21))/M_.params(21);
e1 = M_.params(48);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.254028)^2;
M_.Sigma_e(2, 2) = (0.485825)^2;
M_.Sigma_e(3, 3) = (0.305013)^2;
M_.Sigma_e(4, 4) = (0.570053)^2;
M_.Sigma_e(5, 5) = (0.379025)^2;
M_.Sigma_e(6, 6) = (1.012299)^2;
M_.Sigma_e(7, 7) = (0.354961)^2;
M_.Sigma_e(8, 8) = (0.111101)^2;
options_.irf = 21;
options_.order = 2;
options_.periods = 1000;
var_list_ = {'y';'piyear';'ryear';'e';'u';'ygap'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EA_SWW14_rep_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
